# Pure final-table and anchor-report generator. No plotting.

include(joinpath(@__DIR__, "s30_benchmark.jl"))

const GAME_TABLEDIR = joinpath(GAME_RESULT_ROOT, "tables")

function load_definitive_game_rows(db)
    rows = DBInterface.execute(db, """
        SELECT c.method, r.config_hash, r.problem, r.dimension, r.init_point,
               r.seed_idx, r.converged, r.iterations, r.f_evals,
               r.cpu_time AS legacy_cpu_time,
               gm.natural_residual, gm.duality_gap, gm.min_branch_fraction
        FROM results r JOIN configs c ON c.config_hash=r.config_hash
        JOIN game_final_metrics gm
          ON gm.config_hash=r.config_hash AND gm.problem=r.problem
         AND gm.dimension=r.dimension AND gm.init_point=r.init_point
         AND gm.script=r.script AND gm.production=r.production
        WHERE r.script='s30' AND r.production=1
          AND c.hash_input LIKE '%protocol=game_manuscript_v1%'
          AND c.hash_input LIKE '%reps=3%'
    """) |> DataFrame
    protocol_hash = timing_v2_protocol_hash(
        warmups = 2, repetitions = 3, min_batch_seconds = 0.1,
    )
    return attach_timing_v2(db, rows; min_batch_seconds = 0.1,
                            protocol_hash = protocol_hash)
end

function load_definitive_anchor_rows(db)
    return DBInterface.execute(db, """
        SELECT c.method, a.problem, a.init_point, a.seed_idx,
               a.distance_to_projection, a.displacement, a.distance_to_solution,
               a.projection_distance_error, a.certificate, a.target_hash
        FROM game_anchor_metrics a JOIN configs c ON c.config_hash=a.config_hash
        WHERE a.script='s30' AND a.production=1
          AND c.hash_input LIKE '%protocol=game_manuscript_v1%'
          AND c.hash_input LIKE '%reps=3%'
        ORDER BY c.method, a.seed_idx
    """) |> DataFrame
end

function game_table_stats(df, method, problem)
    rows = df[(df.method .== method) .& (df.problem .== problem), :]
    solved = rows[rows.converged .== 1, :]
    med(col) = nrow(solved) == 0 ? Inf : median(Float64.(solved[!, col]))
    terminal_gap = nrow(rows) == 0 ? Inf : median(Float64.(rows.duality_gap))
    branch_values = collect(skipmissing(rows.min_branch_fraction))
    finite_branches = filter(isfinite, Float64.(branch_values))
    branch = isempty(finite_branches) ? NaN : median(finite_branches)
    return (success = nrow(solved), total = nrow(rows), iter = med(:iterations),
            feval = med(:f_evals), gap = terminal_gap, cpu = med(:timing_ms),
            branch = branch)
end

g1(value) = isfinite(value) ? @sprintf("%.1f", value) : "DNC"
g3(value) = isfinite(value) ? @sprintf("%.3f", value) : "DNC"
ge(value) = isfinite(value) ? @sprintf("%.3e", value) : "DNC"

function write_game_performance_table(df, path)
    open(path, "w") do io
        println(io, "% Auto-generated by saddle_point/s70_tables.jl")
        println(io, "\\begin{table}[H]\\centering")
        println(io, "\\caption{Matrix-game performance under the unit-step natural-residual stopping rule. S reports successes out of ten. Iter, F-evals, and CPU (ms) are medians over successful starts, whereas final duality gap is the median terminal gap over all ten starts so that capped runs retain a numerical diagnostic. Iter and F-evals are displayed without integer rounding. CPU is measured externally with monitoring disabled and is the median of three post-warm-up batches of at least 0.1 seconds per start. HFB is the diagnostic Halpern forward--backward method.}\\label{tab:game_performance}")
        println(io, "\\begin{tabular}{llrrrrr}")
        println(io, "\\toprule")
        println(io, "Instance & Method & S & Iter & F-evals & Final gap & CPU (ms) \\\\")
        println(io, "\\midrule")
        for (instance_index, problem) in enumerate(GAME_INSTANCE_NAMES)
            for method in GAME_METHOD_NAMES
                stats = game_table_stats(df, method, problem)
                println(io, join([replace(problem, "_" => "\\_"), method,
                                  "$(stats.success)/$(stats.total)", g1(stats.iter),
                                  g1(stats.feval), ge(stats.gap), g3(stats.cpu)], " & ") * " \\\\")
            end
            instance_index < length(GAME_INSTANCE_NAMES) && println(io, "\\midrule")
        end
        println(io, "\\bottomrule\n\\end{tabular}\n\\end{table}")
    end
    return path
end

function write_anchor_report(df, path)
    methods = ["AEFBFP", "RFBSM", "IRFBSM"]
    selected = df[in.(df.method, Ref(methods)) .& (df.seed_idx .<= 3), :]
    nrow(selected) >= 9 || error("Anchor report requires AEFBFP, RFBSM, and IRFBSM on at least three anchors.")
    open(path, "w") do io
        println(io, "% Auto-generated by saddle_point/s70_tables.jl")
        println(io, "\\begin{table}[H]\\centering")
        println(io, "\\caption{Anchor diagnostic on the duplicated-identity game. The target is the exact projection of each anchor onto the saddle segment. The last column is the exact maximum projection-certificate value over both segment endpoints.}\\label{tab:game_anchor}")
        println(io, "\\begin{tabular}{llrrrrr}")
        println(io, "\\toprule")
        println(io, "Method & Anchor & \\(\\lVert u_k-P_S(u_0)\\rVert\\) & \\(\\lVert u_0-u_k\\rVert\\) & \\(\\operatorname{dist}(u_0,S)\\) & Distance error & Certificate \\\\")
        println(io, "\\midrule")
        for method in methods
            rows = selected[selected.method .== method, :]
            sort!(rows, :seed_idx)
            for row in eachrow(rows)
                println(io, join([method, String(row.init_point), ge(row.distance_to_projection),
                                  ge(row.displacement), ge(row.distance_to_solution),
                                  ge(row.projection_distance_error), ge(row.certificate)], " & ") * " \\\\")
            end
            method != last(methods) && println(io, "\\midrule")
        end
        println(io, "\\bottomrule\n\\end{tabular}\n\\end{table}")
    end
    return path
end

function game_tables_main()
    configure_reproducible_runtime!()
    mkpath(GAME_TABLEDIR)
    db = open_db(GAME_DB_PATH)
    ensure_game_tables!(db)
    try
        performance = load_definitive_game_rows(db)
        nrow(performance) > 0 || error("No definitive production game rows found.")
        anchors = load_definitive_anchor_rows(db)
        performance_path = write_game_performance_table(performance,
                                                        joinpath(GAME_TABLEDIR, "game_performance.tex"))
        anchor_path = write_anchor_report(anchors, joinpath(GAME_TABLEDIR, "game_anchor.tex"))
        for path in (performance_path, anchor_path)
            println("\n===== $(basename(path)) =====")
            print(read(path, String))
        end
    finally
        SQLite.close(db)
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    game_tables_main()
end
