# Pure table generator for the definitive harmonic-oscillator run. No plotting.

include(joinpath(@__DIR__, "s30_benchmark.jl"))

function load_definitive_oc_rows(db, spec)
    rows = DBInterface.execute(db, """
        SELECT c.method, r.config_hash, r.problem, r.dimension,
               r.dimension AS dim, r.init_point, r.converged, r.iterations,
               r.f_evals, r.cpu_time AS legacy_cpu_time
        FROM results r JOIN configs c ON c.config_hash=r.config_hash
        WHERE r.script='s30' AND r.production=1 AND r.problem=?
          AND c.hash_input LIKE '%protocol=oc_manuscript_v1%'
          AND c.hash_input LIKE '%reps=3%'
    """, (spec.problem_name,)) |> DataFrame
    protocol_hash = timing_v2_protocol_hash(
        warmups = 2, repetitions = 3, min_batch_seconds = 0.1,
    )
    return attach_timing_v2(db, rows; min_batch_seconds = 0.1,
                            protocol_hash = protocol_hash)
end

function definitive_oc_stats(df, method, dim)
    rows = df[(df.method .== method) .& (df.dim .== dim), :]
    solved = rows[rows.converged .== 1, :]
    med(col) = nrow(solved) == 0 ? Inf : median(Float64.(solved[!, col]))
    return (success = nrow(solved), total = nrow(rows), iter = med(:iterations),
            feval = med(:f_evals), cpu = med(:timing_ms))
end

oc1(value) = isfinite(value) ? @sprintf("%.1f", value) : "DNC"
oc3(value) = isfinite(value) ? @sprintf("%.3f", value) : "DNC"

function write_definitive_oc_table(df, spec, path)
    dims = collect(OC_DEFAULT_DIMS)
    open(path, "w") do io
        println(io, "% Auto-generated by optimal_control/harmonic_oscillator/s70_tables.jl")
        println(io, "\\begin{table}[H]\\centering")
        println(io, "\\caption{Harmonic-oscillator optimal-control performance. Medians are over successful starts and displayed without integer rounding; S reports successes out of ten. CPU (ms) is measured externally with monitoring disabled and is the median of three post-warm-up batches of at least 0.1 seconds per start.}\\label{tab:oc_harmonic}")
        println(io, "\\begin{tabular}{l" * repeat("rrrr", length(dims)) * "}")
        println(io, "\\toprule")
        top = ["Method"]
        append!(top, ["\\multicolumn{4}{c}{K=$dim}" for dim in dims])
        println(io, join(top, " & ") * " \\\\")
        rules = String[]
        for j in eachindex(dims)
            lo = 2 + 4 * (j - 1)
            push!(rules, "\\cmidrule(lr){$lo-$(lo + 3)}")
        end
        println(io, join(rules, " "))
        println(io, join(vcat([" "], reduce(vcat, [["S", "Iter", "F-evals", "CPU (ms)"] for _ in dims])), " & ") * " \\\\")
        println(io, "\\midrule")
        for T in OC_METHOD_TYPES
            method = name(T)
            row = [method]
            for dim in dims
                stats = definitive_oc_stats(df, method, dim)
                append!(row, ["$(stats.success)/$(stats.total)", oc1(stats.iter),
                              oc1(stats.feval), oc3(stats.cpu)])
            end
            println(io, join(row, " & ") * " \\\\")
        end
        println(io, "\\bottomrule\n\\end{tabular}\n\\end{table}")
    end
    return path
end

function oc_tables_main()
    configure_reproducible_runtime!()
    tabledir = joinpath(result_root(HARMONIC_OSCILLATOR_SPEC), "tables")
    mkpath(tabledir)
    db = open_db(local_db_path(HARMONIC_OSCILLATOR_SPEC))
    try
        df = load_definitive_oc_rows(db, HARMONIC_OSCILLATOR_SPEC)
        nrow(df) > 0 || error("No definitive harmonic-oscillator production rows found.")
        path = write_definitive_oc_table(df, HARMONIC_OSCILLATOR_SPEC,
                                         joinpath(tabledir, "oc_harmonic.tex"))
        print(read(path, String))
    finally
        SQLite.close(db)
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    oc_tables_main()
end
