# ⚙ AUTO-GENERATED by s20_lhs_parameter_search.jl (2026-06-27T15:28:50.905). DO NOT EDIT BY HAND.
# Robust per-cell winners (n_conv↓, med_iters↑; closest-residual fallback flagged DNC).
# Merge-preserving: a subset --methods sweep re-promotes only those methods; the rest are
# carried over verbatim from the prior file. Consumed by s30. Tracked in git; NOT under results/.

const TUNED_PARAMS = Dict{Tuple{String,String},NamedTuple}(
    ("EPCM", "P1") => (gamma = 2.3190486157142742, vartheta_0 = 0.1192363760170916, vartheta_1 = 0.06934841248324956, zeta = 0.3690594111099482, tau_0 = 1.4658699726787945, delta_rule = :power, sigma_rule = :power, delta_exp = 1.1039406002416698, sigma_exp = 0.802798580041471, sigma_scale = 0.010763326373272942,),  # n_conv=5/5 med_iters=1304 dim=128 hash=47dcc4db6edb
    ("EPCM", "P2") => (gamma = 2.3190486157142742, vartheta_0 = 0.1192363760170916, vartheta_1 = 0.06934841248324956, zeta = 0.3690594111099482, tau_0 = 0.0009693169852024673, delta_rule = :power, sigma_rule = :power, delta_exp = 1.1039406002416698, sigma_exp = 0.802798580041471, sigma_scale = 0.010763326373272942,),  # n_conv=5/5 med_iters=1595 dim=300 hash=c121e99c561f
    ("EPCM", "P3") => (gamma = 1.154967369221579, vartheta_0 = 0.26452509878372205, vartheta_1 = 0.2274896612303786, zeta = 0.3656572342743948, tau_0 = 0.03498071801220992, delta_rule = :power, sigma_rule = :power, delta_exp = 1.2005962917735828, sigma_exp = 0.8702208683741821, sigma_scale = 0.02375599453612374,),  # n_conv=5/5 med_iters=270 dim=100 hash=3ce5c30a1e48
    ("EPCM", "P4") => (gamma = 1.4248878155596616, vartheta_0 = 0.356143178512615, vartheta_1 = 0.15582127138428786, zeta = 0.4488264987980954, tau_0 = 0.21188174778561653, delta_rule = :power, sigma_rule = :power, delta_exp = 1.5031622630657195, sigma_exp = 0.8419052067043837, sigma_scale = 0.011685797532990346,),  # n_conv=5/5 med_iters=4454 dim=512 hash=92715610953b
    ("EPCM", "P5") => (gamma = 2.430772487986246, vartheta_0 = 0.35785292211535796, vartheta_1 = 0.03964112602032998, zeta = 0.5757193559025525, tau_0 = 0.1235684632654701, delta_rule = :power, sigma_rule = :power, delta_exp = 1.9256639718542998, sigma_exp = 0.979997836110596, sigma_scale = 0.011207553050977554,),  # n_conv=0/5 med_iters=-1 dim=256 hash=94fb101ee4c6
    ("EFBFP", "P1") => (vartheta_0 = 0.16352792679693284, vartheta_1 = 0.10301984286321655, tau_0 = 0.17129249439917243, delta_rule = :power, sigma_rule = :power, delta_exp = 1.2039984605258958, sigma_exp = 0.9641401066064197, sigma_scale = 0.012568482505056216,),  # n_conv=5/5 med_iters=717 dim=128 hash=4b8ee70e1a1c
    ("EFBFP", "P2") => (vartheta_0 = 0.12024919451554855, vartheta_1 = 0.04093655741405393, tau_0 = 0.0006387925695880473, delta_rule = :power, sigma_rule = :power, delta_exp = 1.1456073512557394, sigma_exp = 0.9064415483885222, sigma_scale = 0.05787895498290187,),  # n_conv=5/5 med_iters=1377 dim=300 hash=ac9ef5f02a80
    ("EFBFP", "P3") => (vartheta_0 = 0.3233506147828326, vartheta_1 = 0.27480328485232697, tau_0 = 0.04014366849994325, delta_rule = :power, sigma_rule = :power, delta_exp = 1.153326696059928, sigma_exp = 0.773933734169878, sigma_scale = 0.03763688793196508,),  # n_conv=5/5 med_iters=222 dim=100 hash=44213cd4c376
    ("EFBFP", "P4") => (vartheta_0 = 0.34180915160915, vartheta_1 = 0.20327558203924423, tau_0 = 1.9801140760839502, delta_rule = :power, sigma_rule = :power, delta_exp = 1.1153855089925566, sigma_exp = 0.8323222684864107, sigma_scale = 0.010333796870482595,),  # n_conv=5/5 med_iters=4355 dim=512 hash=d6f47b8f6d40
    ("EFBFP", "P5") => (vartheta_0 = 0.20716157800746005, vartheta_1 = 0.13478738369785825, tau_0 = 0.4626364625730651, delta_rule = :power, sigma_rule = :power, delta_exp = 1.9110187434171964, sigma_exp = 0.9889250962799254, sigma_scale = 0.012108598074207718,),  # n_conv=0/5 med_iters=-1 dim=256 hash=4fc76dbd1445
    ("AEFBFP", "P1") => (mu = 0.2908500230997163, tau_0 = 0.07048513645009347, xi_rule = :power, sigma_rule = :power, xi_exp = 1.1341109799770073, sigma_exp = 0.9114402302505438, sigma_scale = 0.011569056226331012,),  # n_conv=5/5 med_iters=1883 dim=128 hash=b0131a68cbb9
    ("AEFBFP", "P2") => (mu = 0.36564073121634655, tau_0 = 7.740936310679319e-5, xi_rule = :power, sigma_rule = :power, xi_exp = 2.145908554810604, sigma_exp = 0.9768262011555431, sigma_scale = 0.010108200861973969,),  # n_conv=5/5 med_iters=572 dim=300 hash=6a8f79f1854a
    ("AEFBFP", "P3") => (mu = 0.32475054644276846, tau_0 = 0.052386951978823273, xi_rule = :power, sigma_rule = :power, xi_exp = 1.1090105055152015, sigma_exp = 0.9709015323685187, sigma_scale = 0.02390913974996533,),  # n_conv=5/5 med_iters=174 dim=100 hash=38cfdd6c844f
    ("AEFBFP", "P4") => (mu = 0.34621889880362916, tau_0 = 0.07257715959765736, xi_rule = :power, sigma_rule = :power, xi_exp = 1.5403020386571031, sigma_exp = 0.9502828562038468, sigma_scale = 0.014042364193454407,),  # n_conv=5/5 med_iters=3508 dim=512 hash=42ba06e6f30d
    ("AEFBFP", "P5") => (mu = 0.36564073121634655, tau_0 = 0.7740936310679318, xi_rule = :power, sigma_rule = :power, xi_exp = 2.145908554810604, sigma_exp = 0.9768262011555431, sigma_scale = 0.010108200861973969,),  # n_conv=0/5 med_iters=-1 dim=256 hash=7c399591894f
    ("MAEFBFP", "P1") => (mu = 0.30, tau_0 = 1.0, xi_rule = :power, sigma_rule = :power, alpha_scale = 0.02, alpha_exp = 2.0, beta_scale = 0.05, beta_exp = 2.0, xi_exp = 2.0, sigma_exp = 1.0, sigma_scale = 1.0,),  # bootstrap defaults (not tuned yet)
    ("MAEFBFP", "P2") => (mu = 0.30, tau_0 = 1.0e-4, xi_rule = :power, sigma_rule = :power, alpha_scale = 0.02, alpha_exp = 2.0, beta_scale = 0.05, beta_exp = 2.0, xi_exp = 2.0, sigma_exp = 1.0, sigma_scale = 1.0,),  # bootstrap defaults (not tuned yet)
    ("MAEFBFP", "P3") => (mu = 0.30, tau_0 = 0.1, xi_rule = :power, sigma_rule = :power, alpha_scale = 0.02, alpha_exp = 2.0, beta_scale = 0.05, beta_exp = 2.0, xi_exp = 2.0, sigma_exp = 1.0, sigma_scale = 1.0,),  # bootstrap defaults (not tuned yet)
    ("MAEFBFP", "P4") => (mu = 0.30, tau_0 = 0.5, xi_rule = :power, sigma_rule = :power, alpha_scale = 0.02, alpha_exp = 2.0, beta_scale = 0.05, beta_exp = 2.0, xi_exp = 2.0, sigma_exp = 1.0, sigma_scale = 1.0,),  # bootstrap defaults (not tuned yet)
    ("MAEFBFP", "P5") => (mu = 0.30, tau_0 = 1.0, xi_rule = :power, sigma_rule = :power, alpha_scale = 0.02, alpha_exp = 2.0, beta_scale = 0.05, beta_exp = 2.0, xi_exp = 2.0, sigma_exp = 1.0, sigma_scale = 1.0,),  # bootstrap defaults (not tuned yet)
    ("MTTM", "P1") => (lambda_0 = 1.1263833342794636, mu = 0.3486167563505491, alpha_rule = :inv_n, beta_rule = :n_minus_1_over_2n,),  # n_conv=5/5 med_iters=2 dim=128 hash=04b09950d085
    ("MTTM", "P2") => (lambda_0 = 1.3336632734512799, mu = 0.49675564216749124, alpha_rule = :inv_n, beta_rule = :n_minus_1_over_2n,),  # n_conv=5/5 med_iters=5271 dim=300 hash=70b824db4e63
    ("MTTM", "P3") => (lambda_0 = 8.487911892873784, mu = 0.5381639000744913, alpha_rule = :inv_n, beta_rule = :n_minus_1_over_2n,),  # n_conv=0/5 med_iters=-1 dim=100 hash=4bb2e93f90d9
    ("MTTM", "P4") => (lambda_0 = 1.655438222472873, mu = 0.9407809632872486, alpha_rule = :inv_n, beta_rule = :n_minus_1_over_2n,),  # n_conv=0/5 med_iters=-1 dim=512 hash=ee5dbe99241c
    ("MTTM", "P5") => (lambda_0 = 19.604382137055406, mu = 0.5813171978556873, alpha_rule = :inv_n, beta_rule = :n_minus_1_over_2n,),  # n_conv=5/5 med_iters=2 dim=256 hash=006c2c2da1db
    ("IMTTM", "P1") => (lambda_0 = 3.770511648009512, mu = 0.4505246420254876, theta = 0.6529989645035369, alpha_rule = :inv_n_plus_1, beta_rule = :tan, epsilon_rule = :hundred_inv_sq,),  # n_conv=5/5 med_iters=7 dim=128 hash=43be431a2221
    ("IMTTM", "P2") => (lambda_0 = 0.2563951331298263, mu = 0.8219978588520049, theta = 0.7248169891790743, alpha_rule = :inv_n_plus_1, beta_rule = :tan, epsilon_rule = :hundred_inv_sq,),  # n_conv=5/5 med_iters=5266 dim=300 hash=3467ec258f5e
    ("IMTTM", "P3") => (lambda_0 = 7.361936480408859, mu = 0.6150892580871706, theta = 0.755073324348203, alpha_rule = :inv_n_plus_1, beta_rule = :tan, epsilon_rule = :hundred_inv_sq,),  # n_conv=0/5 med_iters=-1 dim=100 hash=50ed503f2cf1
    ("IMTTM", "P4") => (lambda_0 = 1.3188008424727606, mu = 0.9355012466705602, theta = 0.4943723524202887, alpha_rule = :inv_n_plus_1, beta_rule = :tan, epsilon_rule = :hundred_inv_sq,),  # n_conv=0/5 med_iters=-1 dim=512 hash=8171fc24fda6
    ("IMTTM", "P5") => (lambda_0 = 1.9378554967436483, mu = 0.4104805551865729, theta = 0.3763403615867141, alpha_rule = :inv_n_plus_1, beta_rule = :tan, epsilon_rule = :hundred_inv_sq,),  # n_conv=5/5 med_iters=27 dim=256 hash=c7dcd6fdb687
    ("IFRAB", "P1") => (delta_0 = 0.12671735602783402, delta_1 = 0.6934924446733519, rbar = 0.46183220157242366, vartheta_bar = 0.013667715863066688, sigma_rule = :izuchukwu_sigma, c_rule = :inv_n_sq_plus_1, vartheta_rule = :n_over_n_plus_1,),  # n_conv=5/5 med_iters=149 dim=128 hash=e8bd92450971
    ("IFRAB", "P2") => (delta_0 = 0.49845223380187303, delta_1 = 0.14169392755493418, rbar = 0.4870718544924276, vartheta_bar = 0.004216434123982124, sigma_rule = :izuchukwu_sigma, c_rule = :inv_n_sq_plus_1, vartheta_rule = :n_over_n_plus_1,),  # n_conv=5/5 med_iters=45 dim=300 hash=44fc7bf007f7
    ("IFRAB", "P3") => (delta_0 = 0.37370137103064965, delta_1 = 0.16757112201662225, rbar = 0.3035709770946262, vartheta_bar = 0.04429344168520413, sigma_rule = :izuchukwu_sigma, c_rule = :inv_n_sq_plus_1, vartheta_rule = :n_over_n_plus_1,),  # n_conv=5/5 med_iters=403 dim=100 hash=0492b0cc96bd
    ("IFRAB", "P4") => (delta_0 = 0.10559732901438722, delta_1 = 0.3800628062358762, rbar = 0.47820888412887486, vartheta_bar = 0.006893080801974919, sigma_rule = :izuchukwu_sigma, c_rule = :inv_n_sq_plus_1, vartheta_rule = :n_over_n_plus_1,),  # n_conv=5/5 med_iters=3919 dim=512 hash=6254fbf44b2d
    ("IFRAB", "P5") => (delta_0 = 0.22926064188112605, delta_1 = 0.10878570873174417, rbar = 0.4122723454831632, vartheta_bar = 0.025541087223298342, sigma_rule = :izuchukwu_sigma, c_rule = :inv_n_sq_plus_1, vartheta_rule = :n_over_n_plus_1,),  # n_conv=0/5 med_iters=-1 dim=256 hash=9639a9d33d95
    ("SFRBM", "P1") => (lambda_minus1 = 0.009765209358933342, lambda_0 = 0.009765209358933342, mu = 0.2867422952496227, theta = 0.646095862209616, beta_rule = :yao,),  # n_conv=0/5 med_iters=-1 dim=128 hash=fe154e2d040c
    ("SFRBM", "P2") => (lambda_minus1 = 0.009765209358933342, lambda_0 = 0.009765209358933342, mu = 0.2867422952496227, theta = 0.646095862209616, beta_rule = :yao,),  # n_conv=5/5 med_iters=1174 dim=300 hash=860e586982da
    ("SFRBM", "P3") => (lambda_minus1 = 0.009765209358933342, lambda_0 = 0.009765209358933342, mu = 0.2867422952496227, theta = 0.646095862209616, beta_rule = :yao,),  # n_conv=0/5 med_iters=-1 dim=100 hash=4c35f4de8011
    ("SFRBM", "P4") => (lambda_minus1 = 0.002101438786850165, lambda_0 = 0.002101438786850165, mu = 0.04619454247339882, theta = 1.554083691585139, beta_rule = :yao,),  # n_conv=0/5 med_iters=-1 dim=512 hash=addcf072a501
    ("SFRBM", "P5") => (lambda_minus1 = 0.009765209358933342, lambda_0 = 0.009765209358933342, mu = 0.2867422952496227, theta = 0.646095862209616, beta_rule = :yao,),  # n_conv=0/5 med_iters=-1 dim=256 hash=a2105b2364f1
    ("VAFBS", "P1") => (delta = 0.5, ell = 0.5, mu = 0.5, gamma = 1.0, alpha_rule = :c_over_n, alpha_scale = 0.01, f_scale = 0.9,),  # bootstrap defaults (not tuned yet)
    ("VAFBS", "P2") => (delta = 0.5, ell = 0.5, mu = 0.5, gamma = 1.0, alpha_rule = :c_over_n, alpha_scale = 0.01, f_scale = 0.9,),  # bootstrap defaults (not tuned yet)
    ("VAFBS", "P3") => (delta = 0.5, ell = 0.5, mu = 0.5, gamma = 1.0, alpha_rule = :c_over_n, alpha_scale = 0.01, f_scale = 0.9,),  # bootstrap defaults (not tuned yet)
    ("VAFBS", "P4") => (delta = 0.5, ell = 0.5, mu = 0.5, gamma = 1.0, alpha_rule = :c_over_n, alpha_scale = 0.01, f_scale = 0.9,),  # bootstrap defaults (not tuned yet)
    ("VAFBS", "P5") => (delta = 0.5, ell = 0.5, mu = 0.5, gamma = 1.0, alpha_rule = :c_over_n, alpha_scale = 0.01, f_scale = 0.9,),  # bootstrap defaults (not tuned yet)
    ("MDITSM", "P1") => (mu = 0.9, lambda_1 = 0.1, alpha_rule = :one_minus_scale_over_base_pow_n, alpha_scale = 1.0, alpha_base = 10.0, beta_rule = :cap_minus_inv_n_plus_shift, beta_cap = 0.1, beta_shift = 1000.0, theta_rule = :cap_minus_inv_n_plus_shift, theta_cap = 0.45, theta_shift = 1000.0, mu_rule = :scale_over_n_pow, mu_scale = 1.0, mu_exp = 2.0, p_rule = :scale_over_n_pow, p_scale = 1.0, p_exp = 2.0,),  # bootstrap defaults (not tuned yet)
    ("MDITSM", "P2") => (mu = 0.9, lambda_1 = 0.1, alpha_rule = :one_minus_scale_over_base_pow_n, alpha_scale = 1.0, alpha_base = 10.0, beta_rule = :cap_minus_inv_n_plus_shift, beta_cap = 0.1, beta_shift = 1000.0, theta_rule = :cap_minus_inv_n_plus_shift, theta_cap = 0.45, theta_shift = 1000.0, mu_rule = :scale_over_n_pow, mu_scale = 1.0, mu_exp = 2.0, p_rule = :scale_over_n_pow, p_scale = 1.0, p_exp = 2.0,),  # bootstrap defaults (not tuned yet)
    ("MDITSM", "P3") => (mu = 0.9, lambda_1 = 0.1, alpha_rule = :one_minus_scale_over_base_pow_n, alpha_scale = 1.0, alpha_base = 10.0, beta_rule = :cap_minus_inv_n_plus_shift, beta_cap = 0.1, beta_shift = 1000.0, theta_rule = :cap_minus_inv_n_plus_shift, theta_cap = 0.45, theta_shift = 1000.0, mu_rule = :scale_over_n_pow, mu_scale = 1.0, mu_exp = 2.0, p_rule = :scale_over_n_pow, p_scale = 1.0, p_exp = 2.0,),  # bootstrap defaults (not tuned yet)
    ("MDITSM", "P4") => (mu = 0.9, lambda_1 = 0.1, alpha_rule = :one_minus_scale_over_base_pow_n, alpha_scale = 1.0, alpha_base = 10.0, beta_rule = :cap_minus_inv_n_plus_shift, beta_cap = 0.1, beta_shift = 1000.0, theta_rule = :cap_minus_inv_n_plus_shift, theta_cap = 0.45, theta_shift = 1000.0, mu_rule = :scale_over_n_pow, mu_scale = 1.0, mu_exp = 2.0, p_rule = :scale_over_n_pow, p_scale = 1.0, p_exp = 2.0,),  # bootstrap defaults (not tuned yet)
    ("MDITSM", "P5") => (mu = 0.9, lambda_1 = 0.1, alpha_rule = :one_minus_scale_over_base_pow_n, alpha_scale = 1.0, alpha_base = 10.0, beta_rule = :cap_minus_inv_n_plus_shift, beta_cap = 0.1, beta_shift = 1000.0, theta_rule = :cap_minus_inv_n_plus_shift, theta_cap = 0.45, theta_shift = 1000.0, mu_rule = :scale_over_n_pow, mu_scale = 1.0, mu_exp = 2.0, p_rule = :scale_over_n_pow, p_scale = 1.0, p_exp = 2.0,),  # bootstrap defaults (not tuned yet)
    ("MFRBSM", "P1") => (lambda_minus1 = 0.1, lambda_0 = 0.1, mu = 0.49,),  # bootstrap defaults (not tuned yet)
    ("MFRBSM", "P2") => (lambda_minus1 = 0.1, lambda_0 = 0.1, mu = 0.49,),  # bootstrap defaults (not tuned yet)
    ("MFRBSM", "P3") => (lambda_minus1 = 0.1, lambda_0 = 0.1, mu = 0.49,),  # bootstrap defaults (not tuned yet)
    ("MFRBSM", "P4") => (lambda_minus1 = 0.1, lambda_0 = 0.1, mu = 0.49,),  # bootstrap defaults (not tuned yet)
    ("MFRBSM", "P5") => (lambda_minus1 = 0.1, lambda_0 = 0.1, mu = 0.49,),  # bootstrap defaults (not tuned yet)
    ("RFBSM", "P1") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9,),  # bootstrap defaults (not tuned yet)
    ("RFBSM", "P2") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9,),  # bootstrap defaults (not tuned yet)
    ("RFBSM", "P3") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9,),  # bootstrap defaults (not tuned yet)
    ("RFBSM", "P4") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9,),  # bootstrap defaults (not tuned yet)
    ("RFBSM", "P5") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9,),  # bootstrap defaults (not tuned yet)
    ("IRFBSM", "P1") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9, alpha = 0.04,),  # bootstrap defaults (not tuned yet)
    ("IRFBSM", "P2") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9, alpha = 0.04,),  # bootstrap defaults (not tuned yet)
    ("IRFBSM", "P3") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9, alpha = 0.04,),  # bootstrap defaults (not tuned yet)
    ("IRFBSM", "P4") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9, alpha = 0.04,),  # bootstrap defaults (not tuned yet)
    ("IRFBSM", "P5") => (lambda_0 = 1.0, theta = 1.0, mu = 0.9, alpha = 0.04,),  # bootstrap defaults (not tuned yet)
)

const TUNED_CONVERGED = Dict{Tuple{String,String},Bool}(
    ("EPCM", "P1") => true,
    ("EPCM", "P2") => true,
    ("EPCM", "P3") => true,
    ("EPCM", "P4") => true,
    ("EPCM", "P5") => false,
    ("EFBFP", "P1") => true,
    ("EFBFP", "P2") => true,
    ("EFBFP", "P3") => true,
    ("EFBFP", "P4") => true,
    ("EFBFP", "P5") => false,
    ("AEFBFP", "P1") => true,
    ("AEFBFP", "P2") => true,
    ("AEFBFP", "P3") => true,
    ("AEFBFP", "P4") => true,
    ("AEFBFP", "P5") => false,
    ("MAEFBFP", "P1") => true,
    ("MAEFBFP", "P2") => true,
    ("MAEFBFP", "P3") => true,
    ("MAEFBFP", "P4") => true,
    ("MAEFBFP", "P5") => true,
    ("MTTM", "P1") => true,
    ("MTTM", "P2") => true,
    ("MTTM", "P3") => false,
    ("MTTM", "P4") => false,
    ("MTTM", "P5") => true,
    ("IMTTM", "P1") => true,
    ("IMTTM", "P2") => true,
    ("IMTTM", "P3") => false,
    ("IMTTM", "P4") => false,
    ("IMTTM", "P5") => true,
    ("IFRAB", "P1") => true,
    ("IFRAB", "P2") => true,
    ("IFRAB", "P3") => true,
    ("IFRAB", "P4") => true,
    ("IFRAB", "P5") => false,
    ("SFRBM", "P1") => false,
    ("SFRBM", "P2") => true,
    ("SFRBM", "P3") => false,
    ("SFRBM", "P4") => false,
    ("SFRBM", "P5") => false,
    ("VAFBS", "P1") => true,
    ("VAFBS", "P2") => true,
    ("VAFBS", "P3") => true,
    ("VAFBS", "P4") => true,
    ("VAFBS", "P5") => true,
    ("MDITSM", "P1") => true,
    ("MDITSM", "P2") => true,
    ("MDITSM", "P3") => true,
    ("MDITSM", "P4") => true,
    ("MDITSM", "P5") => true,
    ("MFRBSM", "P1") => true,
    ("MFRBSM", "P2") => true,
    ("MFRBSM", "P3") => true,
    ("MFRBSM", "P4") => true,
    ("MFRBSM", "P5") => true,
    ("RFBSM", "P1") => true,
    ("RFBSM", "P2") => true,
    ("RFBSM", "P3") => true,
    ("RFBSM", "P4") => true,
    ("RFBSM", "P5") => true,
    ("IRFBSM", "P1") => true,
    ("IRFBSM", "P2") => true,
    ("IRFBSM", "P3") => true,
    ("IRFBSM", "P4") => true,
    ("IRFBSM", "P5") => true,
)
