# ============================================================================
# competitors_original_parameters_presets.jl
# ============================================================================
#
# The COMPETITOR baselines' ORIGINAL (source-paper) parameter presets.
# Hand-maintained; the canonical record of "the authors' own settings".
#
#   :paper      — the source-paper verbatim values (used by s28 home-cell
#                 validation).
#   :P1.. :P4   — per-problem search CENTRES for the s20 LHS sweep (currently
#                 seeded equal to :paper; edit here if a problem needs a
#                 different starting point).
#
# The PROPOSED method (EPCM) is not a competitor and has no entry here; its
# manuscript defaults live in src/algorithm_types.jl (EPCM_PRESETS), and its
# fine-tuned values — like every method's — are written by s20 to
# configs/autogenerated_finetuned_parameters_presets.jl.
#
# Loaded by src/includes.jl right after algorithm_types.jl, so the
# `T(preset::Symbol)` constructors (defined there) resolve these dicts at call
# time. Tracked in git (NOT under results/).

# ── MTTM (Gibali2018 Alg 1) — Ex 3 / Ex 4 verbatim ──────────────────────────
const MTTM_PRESETS = Dict{Symbol,NamedTuple}(
    :paper => (lambda_0=7.55, mu=0.85, alpha_rule=:inv_n, beta_rule=:n_minus_1_over_2n),
    :P1    => (lambda_0=7.55, mu=0.85, alpha_rule=:inv_n, beta_rule=:n_minus_1_over_2n),
    :P2    => (lambda_0=7.55, mu=0.85, alpha_rule=:inv_n, beta_rule=:n_minus_1_over_2n),
    :P3    => (lambda_0=7.55, mu=0.85, alpha_rule=:inv_n, beta_rule=:n_minus_1_over_2n),
    :P4    => (lambda_0=7.55, mu=0.85, alpha_rule=:inv_n, beta_rule=:n_minus_1_over_2n),
)

# ── IMTTM (Tan2022a Alg 3.3) ────────────────────────────────────────────────
# :paper keeps Tan's Ex 5.1 home value (λ_0=0.01); the benchmark per-problem
# centres use Tan's default λ_0=1 (Ex 5.2/5.3 are well-conditioned).
const IMTTM_PRESETS = Dict{Symbol,NamedTuple}(
    :paper => (lambda_0=0.01, mu=0.5, theta=0.5,
               alpha_rule=:inv_n_plus_1, beta_rule=:tan, epsilon_rule=:hundred_inv_sq),
    :P1    => (lambda_0=1.0,  mu=0.5, theta=0.5,
               alpha_rule=:inv_n_plus_1, beta_rule=:tan, epsilon_rule=:hundred_inv_sq),
    :P2    => (lambda_0=1.0,  mu=0.5, theta=0.5,
               alpha_rule=:inv_n_plus_1, beta_rule=:tan, epsilon_rule=:hundred_inv_sq),
    :P3    => (lambda_0=1.0,  mu=0.5, theta=0.5,
               alpha_rule=:inv_n_plus_1, beta_rule=:tan, epsilon_rule=:hundred_inv_sq),
    :P4    => (lambda_0=1.0,  mu=0.5, theta=0.5,
               alpha_rule=:inv_n_plus_1, beta_rule=:tan, epsilon_rule=:hundred_inv_sq),
)

# ── IFRAB (Izuchukwu2023 Alg 4.5) — Ex 6.2 home-cell values ─────────────────
const IFRAB_PRESETS = Dict{Symbol,NamedTuple}(
    :paper => (delta_0=0.1, delta_1=0.3, rbar=0.3, vartheta_bar=0.04,
               sigma_rule=:izuchukwu_sigma, c_rule=:inv_n_sq_plus_1,
               vartheta_rule=:n_over_n_plus_1),
    :P1    => (delta_0=0.1, delta_1=0.3, rbar=0.3, vartheta_bar=0.04,
               sigma_rule=:izuchukwu_sigma, c_rule=:inv_n_sq_plus_1,
               vartheta_rule=:n_over_n_plus_1),
    :P2    => (delta_0=0.1, delta_1=0.3, rbar=0.3, vartheta_bar=0.04,
               sigma_rule=:izuchukwu_sigma, c_rule=:inv_n_sq_plus_1,
               vartheta_rule=:n_over_n_plus_1),
    :P3    => (delta_0=0.1, delta_1=0.3, rbar=0.3, vartheta_bar=0.04,
               sigma_rule=:izuchukwu_sigma, c_rule=:inv_n_sq_plus_1,
               vartheta_rule=:n_over_n_plus_1),
    :P4    => (delta_0=0.1, delta_1=0.3, rbar=0.3, vartheta_bar=0.04,
               sigma_rule=:izuchukwu_sigma, c_rule=:inv_n_sq_plus_1,
               vartheta_rule=:n_over_n_plus_1),
)

# ── SFRBM (Yao2024 Alg 2) — Ex 4.1–4.3 verbatim ─────────────────────────────
const SFRBM_PRESETS = Dict{Symbol,NamedTuple}(
    :paper => (lambda_minus1=1.0e-4, lambda_0=1.0e-4, mu=1.0e-4, theta=10.0, beta_rule=:yao),
    :P1    => (lambda_minus1=1.0e-4, lambda_0=1.0e-4, mu=1.0e-4, theta=10.0, beta_rule=:yao),
    :P2    => (lambda_minus1=1.0e-4, lambda_0=1.0e-4, mu=1.0e-4, theta=10.0, beta_rule=:yao),
    :P3    => (lambda_minus1=1.0e-4, lambda_0=1.0e-4, mu=1.0e-4, theta=10.0, beta_rule=:yao),
    :P4    => (lambda_minus1=1.0e-4, lambda_0=1.0e-4, mu=1.0e-4, theta=10.0, beta_rule=:yao),
)
