# Pure table generator for the definitive compressed-sensing run. No plotting.

include(joinpath(@__DIR__, "s30_benchmark.jl"))

const CS_TABLEDIR = joinpath(RESULT_ROOT, "tables")

function load_cs_table_rows(db)
    ensure_local_tables!(db)
    rows = DBInterface.execute(db, """
        SELECT c.method, r.config_hash, r.problem, r.dimension, r.init_point,
               r.converged, r.iterations, r.f_evals,
               r.cpu_time AS legacy_cpu_time,
               m.objective, m.reconstruction_mse, m.common_residual
        FROM results r
        JOIN configs c ON c.config_hash=r.config_hash
        LEFT JOIN cs_final_metrics m
          ON m.config_hash=r.config_hash AND m.problem=r.problem
         AND m.dimension=r.dimension AND m.init_point=r.init_point
         AND m.production=r.production
        WHERE r.script='s30' AND r.production=1
          AND c.hash_input LIKE '%protocol=manuscript_v1%'
          AND c.hash_input LIKE '%reps=3%'
    """) |> DataFrame
    protocol_hash = timing_v2_protocol_hash(
        warmups = 2, repetitions = 3, min_batch_seconds = 0.1,
    )
    return attach_timing_v2(db, rows; min_batch_seconds = 0.1,
                            protocol_hash = protocol_hash)
end

function cs_table_stats(df, method, problem)
    rows = df[(df.method .== method) .& (df.problem .== problem), :]
    solved = rows[rows.converged .== 1, :]
    med(col) = nrow(solved) == 0 ? Inf : median(Float64.(collect(skipmissing(solved[!, col]))))
    return (success = nrow(solved), total = nrow(rows), iter = med(:iterations),
            feval = med(:f_evals), cpu = med(:timing_ms), objective = med(:objective),
            mse = med(:reconstruction_mse), common_residual = med(:common_residual))
end

finite1(value) = isfinite(value) ? @sprintf("%.1f", value) : "DNC"
finite3(value) = isfinite(value) ? @sprintf("%.3f", value) : "DNC"
finitee(value) = isfinite(value) ? @sprintf("%.3e", value) : "DNC"

function write_cs_performance_table(df, cases, path, label)
    open(path, "w") do io
        println(io, "% Auto-generated by compressed_sensing/s70_tables.jl")
        println(io, "\\begin{table}[H]\\centering")
        println(io, "\\caption{Compressed-sensing performance for Cases $(first(cases))--$(last(cases)). Medians are taken over successful starts and displayed without integer rounding; S reports successes out of ten. CPU (ms) is measured externally with monitoring disabled and is the median of three post-warm-up batches of at least 0.1 seconds per start.}\\label{$label}")
        println(io, "\\begin{tabular}{l" * repeat("rrrr", length(cases)) * "}")
        println(io, "\\toprule")
        top = ["Method"]
        append!(top, ["\\multicolumn{4}{c}{Case $i}" for i in cases])
        println(io, join(top, " & ") * " \\\\")
        rules = String[]
        for j in eachindex(cases)
            lo = 2 + 4 * (j - 1)
            push!(rules, "\\cmidrule(lr){$lo-$(lo + 3)}")
        end
        println(io, join(rules, " "))
        header = [" "]
        for _ in cases
            append!(header, ["S", "Iter", "F-evals", "CPU (ms)"])
        end
        println(io, join(header, " & ") * " \\\\")
        println(io, "\\midrule")
        for T in METHOD_TYPES
            method = name(T)
            row = [method]
            for index in cases
                stats = cs_table_stats(df, method, DEFAULT_CASES[index].problem)
                append!(row, ["$(stats.success)/$(stats.total)", finite1(stats.iter),
                              finite1(stats.feval), finite3(stats.cpu)])
            end
            println(io, join(row, " & ") * " \\\\")
        end
        println(io, "\\bottomrule\n\\end{tabular}\n\\end{table}")
    end
    return path
end

function write_cs_accuracy_table(df, path)
    open(path, "w") do io
        println(io, "% Auto-generated by compressed_sensing/s70_tables.jl")
        println(io, "\\begin{table}[H]\\centering")
        println(io, "\\caption{Compressed-sensing terminal accuracy. The objective, reconstruction MSE, and common \\(1/L\\)-scaled fixed-point residual are medians over converged starts. The common residual is a terminal diagnostic only; runs stop on two consecutive successive-displacement tests.}\\label{tab:cs_accuracy}")
        println(io, "\\begin{tabular}{llrrrr}")
        println(io, "\\toprule")
        println(io, "Case & Method & S & Objective & MSE & Common residual \\\\")
        println(io, "\\midrule")
        for (index, case) in enumerate(DEFAULT_CASES)
            for T in METHOD_TYPES
                method = name(T)
                stats = cs_table_stats(df, method, case.problem)
                println(io, join([string(index), method, "$(stats.success)/$(stats.total)",
                                  finitee(stats.objective), finitee(stats.mse),
                                  finitee(stats.common_residual)], " & ") * " \\\\")
            end
            index < length(DEFAULT_CASES) && println(io, "\\midrule")
        end
        println(io, "\\bottomrule\n\\end{tabular}\n\\end{table}")
    end
    return path
end

function cs_tables_main()
    configure_reproducible_runtime!()
    mkpath(CS_TABLEDIR)
    db = open_db(DB_PATH)
    try
        df = load_cs_table_rows(db)
        nrow(df) > 0 || error("No definitive production CS rows found.")
        paths = [
            write_cs_performance_table(df, 1:2, joinpath(CS_TABLEDIR, "cs_results_12.tex"), "tab:cs_results_12"),
            write_cs_performance_table(df, 3:4, joinpath(CS_TABLEDIR, "cs_results_34.tex"), "tab:cs_results_34"),
            write_cs_accuracy_table(df, joinpath(CS_TABLEDIR, "cs_accuracy.tex")),
        ]
        for path in paths
            println("\n===== $(basename(path)) =====")
            print(read(path, String))
        end
    finally
        SQLite.close(db)
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    cs_tables_main()
end
