# algorithm_types.jl — Algorithm type hierarchy + per-problem presets.
#
# Defines the AbstractAlgorithm hierarchy, the concrete algorithm
# structs (EPCM, EFBFP, AEFBFP, MAEFBFP, VAFBS, MDITSM, MFRBSM, RFBSM, IRFBSM, MTTM, IMTTM, IFRAB, SFRBM),
# per-algorithm preset registries,
# and the project's trait methods (`name`, `version`). Method bodies for
# `solve(::T, prob, x0; stopping, observers)` live in `algorithm.jl`
# (Steps 7 and 10).
#
# Design references:
#  - script_port_plan.md §4 Q3 (post-review revision), §5.1 algorithm_types.jl row.
#  - paper/main.tex §Parameter choices (lines 1593-1626) — source-paper defaults
#    and per-problem `tau_0` (EPCM) / `lambda_0` (IMTTM) adjustments.
#  - plan_review_findings.md B2 (IFRAB ϑ_n = ϑ̄·n/(n+1) parameter-free) /
#    B4 (per-(method, problem) tuning).
#
# Design principles:
#  - Algorithm INSTANCES carry their parameters as concrete-typed fields.
#  - Rule-selectors (e.g. α_n = 1/(n+1)) are encoded as `Symbol` tags the
#    solver dispatches on. **No `Function`-typed fields** — that would
#    make `make_config_hash` non-reproducible (gensym counter leaks into
#    repr(Function)).
#  - Presets are keyed by `Symbol`: `:P1`–`:P5` (per-problem; EPCM's in
#    `EPCM_PRESETS` here = manuscript defaults / s20 search centre, the baselines'
#    in `configs/competitors_original_…`) plus `:paper` (baselines' source-paper
#    defaults for `s28_validate_baselines.jl`). Fine-tuned winners are written by
#    s20 to `configs/autogenerated_finetuned_…`, NOT back into these dicts.
#  - Outer constructor `T(preset::Symbol; kwargs...)` merges the preset
#    NamedTuple with explicit kwarg overrides.
#  - Trait methods `name(::Type{T})` and `version(::Type{T})` feed
#    `make_config_hash(alg, prob_id, eps, maxiter)`.

# ============================================================================
# Abstract type + interface declaration
# ============================================================================

"""
    AbstractAlgorithm

Root abstract type for all monotone-inclusion solvers in this project.

## Interface (each concrete subtype `T` must implement):

  - `name(::Type{T})::String`             — short tag, e.g. `"EPCM"`.
  - `version(::Type{T})::VersionNumber`   — semver; bumps produce fresh
                                            DB hashes via `make_config_hash`.
  - `solve(alg::T, prob::TestProblem, x0::Vector{Float64}; stopping::Tuple, observers::Tuple) -> SolverResult`
                                            — body in `algorithm.jl`.

## Conventions

  - Const registry `<ALG>_PRESETS::Dict{Symbol,NamedTuple}` with keys
    `:P1, :P2, :P3, :paper`.
  - Outer constructor `T(preset::Symbol; kwargs...) = T(; merge(preset, kwargs)...)`.

## Field-typing rules

  - All param fields must be concretely typed (`Float64`, `Symbol`, ...).
  - **No `Function`-typed fields.** Encode rule-selectors as `Symbol`
    tags the `solve` method dispatches on. This keeps `make_config_hash`
    reproducible across Julia sessions (gensym counter would otherwise
    leak into `repr(Function)`).

## Versioning discipline

  - PATCH bump: bug fix in the solver body (same math, different output bits).
  - MINOR bump: logic change (different mathematical output).
  - MAJOR bump: signature break.
  - Bumping the version produces a different `config_hash`; old DB rows
    preserve historical state; new runs land in fresh rows.
"""
abstract type AbstractAlgorithm end

"""
    name(::Type{T}) where {T <: AbstractAlgorithm} -> String

Short tag for `T` (e.g. `"EPCM"`). Used as the `method` column in the DB
and in performance-profile legends. Each concrete subtype implements this.

Convenience forwarder: `name(alg::AbstractAlgorithm) = name(typeof(alg))`.
"""
function name end
name(alg::AbstractAlgorithm) = name(typeof(alg))

"""
    version(::Type{T}) where {T <: AbstractAlgorithm} -> VersionNumber

Semver for `T`. Bumping it produces a fresh `config_hash` for every run.
Use `VersionNumber` (not `String`) so results can be filtered with
`v"1.0.0" ≤ ver < v"2.0.0"` semantics. Each concrete subtype implements this.

Convenience forwarder: `version(alg::AbstractAlgorithm) = version(typeof(alg))`.
"""
function version end
version(alg::AbstractAlgorithm) = version(typeof(alg))

"""
    solve(alg::AbstractAlgorithm, prob::TestProblem, x0::Vector{Float64};
          stopping::Tuple, observers::Tuple=()) -> SolverResult

Solve the monotone inclusion `0 ∈ A(x) + B(x)` defined by `prob`, starting
from `x0`, using algorithm `alg`. Method bodies live in `algorithm.jl`
(Step 7 for EPCM, Step 10 for the baseline methods). Each method honours
the 9-step "Solver responsibility" contract in `callbacks.jl`'s
`SolverState` docstring.
"""
function solve end

# ============================================================================
# EPCM — Extrapolated Projection–Contraction Method (proposed)
# ============================================================================
#
# Source: this paper, `\EPCM` macro. Manuscript §Parameter choices lines 1598-1605:
#   γ=1, ϑ_0=0.2, ϑ_1=0.1, ζ=0.5; δ_k = 1/(k+1)², σ_k = 1/(k+2).
#   τ_0: 0.01 (P1), 1e-4 (P2), 0.1 (P3).
#   (μ is a proof-only constant post-refactor — not a field; see struct docstring.)
#
# σ_k, δ_k are parametrized (Step 11-2) as a sensitivity-study family staying
# inside the Algorithm 1 admissibility envelope (σ_k∈(0,1),→0,Σ=∞; δ_k≥0,Σ<∞):
#   σ_k = sigma_scale / (k+2)^sigma_exp   (sigma_exp∈(0,1]; σ_0 = sigma_scale/2^sigma_exp < 1)
#   δ_k = 1 / (k+1)^delta_exp             (delta_exp > 1; or delta_rule=:zero ⟹ δ_k≡0)
# Defaults sigma_scale=1, sigma_exp=1, delta_exp=2 reproduce σ_k=1/(k+2), δ_k=1/(k+1)².

"""
    EPCM(; gamma, vartheta_0, vartheta_1, zeta, tau_0,
           delta_rule, sigma_rule, delta_exp, sigma_exp, sigma_scale)
    EPCM(preset::Symbol; kwargs...)

Extrapolated projection–contraction method (proposed). Parameters per
manuscript §Parameter choices. All kwargs are required in the explicit
constructor; the preset constructor fills from `EPCM_PRESETS`.

## Parametrized sequences (Step 11-2 sensitivity-study family)

  - `sigma_rule = :power` ↦ σ_k = `sigma_scale` / (k+2)^`sigma_exp`.
    Admissibility (Algorithm 1: σ_k∈(0,1), σ_k→0, Σσ_k=∞) requires
    `sigma_exp ∈ (0,1]` and σ_0 = `sigma_scale`/2^`sigma_exp` < 1.
    Default `sigma_exp=1, sigma_scale=1` ⟹ σ_k = 1/(k+2) (Lieder-optimal Halpern).
    `sigma_exp<1` strengthens anchoring; `sigma_scale<1` weakens it.
  - `delta_rule = :power` ↦ δ_k = 1 / (k+1)^`delta_exp`.
    Admissibility (Σδ_k<∞) requires `delta_exp > 1`. Default `delta_exp=2`
    ⟹ δ_k = 1/(k+1)² (total step-growth headroom Π(1+δ_k) ≈ 3.68×).
    Smaller `delta_exp` ⟹ more headroom (helps τ_0 robustness); larger ⟹ less.
  - `delta_rule = :zero` ↦ δ_k ≡ 0 (monotone-shrink baseline; `delta_exp` ignored).

Validated at `solve` entry; out-of-envelope values throw `ArgumentError`.

Note: the proof-side constant `μ ∈ (1, 2)` (with `μ·ϑ_0 < √(γ/(2(2γ+1)))`)
is NOT a field of this struct. Its existence is guaranteed by the strict
admissibility constraint `ϑ_0 < √(γ/(2(2γ+1)))` (validated at `solve`
entry); the iteration does not depend on which admissible μ is chosen.
"""
struct EPCM <: AbstractAlgorithm
    gamma::Float64
    vartheta_0::Float64
    vartheta_1::Float64
    zeta::Float64
    tau_0::Float64
    delta_rule::Symbol
    sigma_rule::Symbol
    delta_exp::Float64
    sigma_exp::Float64
    sigma_scale::Float64

    function EPCM(; gamma::Float64, vartheta_0::Float64, vartheta_1::Float64,
                  zeta::Float64, tau_0::Float64,
                  delta_rule::Symbol, sigma_rule::Symbol,
                  delta_exp::Float64, sigma_exp::Float64, sigma_scale::Float64)
        return new(gamma, vartheta_0, vartheta_1, zeta, tau_0,
                   delta_rule, sigma_rule, delta_exp, sigma_exp, sigma_scale)
    end
end

"""
EPCM presets keyed by `Symbol`. The per-problem entries (`:P1`–`:P5`) are the
manuscript defaults (incl. the per-problem `tau_0`) and serve as the s20 LHS
search CENTRE. The fine-tuned winners are written by s20 to
`configs/autogenerated_finetuned_parameters_presets.jl` (consumed by s30) —
NOT back into this dict. The `delta_exp=2, sigma_exp=1, sigma_scale=1` defaults
reproduce the manuscript's `δ_k=1/(k+1)²`, `σ_k=1/(k+2)`.

There is no `:paper` preset for EPCM — EPCM IS this paper. Use a per-
problem preset and override `tau_0` if you need a custom scaling.
"""
const EPCM_PRESETS = Dict{Symbol,NamedTuple}(
    # τ_0 scaled per problem (OAT centre, tuned later). P1=Volterra (L≈0.4),
    # P2=ℓ1+quad (L=2), P3=control (L=4), P4=LASSO (L=1), P5=ℓ₂ example (L=1).
    :P1 => (gamma=1.0, vartheta_0=0.2, vartheta_1=0.1, zeta=0.5, tau_0=1.0,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P2 => (gamma=1.0, vartheta_0=0.2, vartheta_1=0.1, zeta=0.5, tau_0=1.0e-4,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P3 => (gamma=1.0, vartheta_0=0.2, vartheta_1=0.1, zeta=0.5, tau_0=0.1,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P4 => (gamma=1.0, vartheta_0=0.2, vartheta_1=0.1, zeta=0.5, tau_0=0.5,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P5 => (gamma=1.0, vartheta_0=0.2, vartheta_1=0.1, zeta=0.5, tau_0=1.0,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
)

function EPCM(preset::Symbol; kwargs...)
    haskey(EPCM_PRESETS, preset) ||
        throw(ArgumentError("Unknown EPCM preset :$preset. Known: $(join(sort(collect(keys(EPCM_PRESETS))), ", "))"))
    return EPCM(; merge(EPCM_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{EPCM})    = "EPCM"
version(::Type{EPCM}) = v"1.3.0"   # 1.1.0→1.2.0: θ_k clamped at 0 via max{0,·} (PC descent needs θ_k≥0; notes §24.3). 1.2.0→1.3.0: stepsize threshold corrected ϑ₀·τ_k→ϑ₀/τ_k (matches paper/proof) + half-split admissibility ϑ₀<√(γ/(2(3γ+1))), ζ<4/(3+γ). config_hash changes ⟹ fresh results, no collision with pre-1.3.0.

# ============================================================================
# EFBFP — Extrapolated Forward–Backward–Forward (manuscript Algorithm 2)
# ============================================================================
#
# EFBFP = EPCM with the projection–contraction step removed: Steps 4–6 of
# Algorithm 1 collapse to x_{k+1} = v_k (the forward correction IS the update),
# dropping the parameters γ and ζ. Single-call, Halpern-anchored Tseng/FBF with
# the SAME ϑ-adaptive stepsize as EPCM. No convergence theorem yet — implemented
# for benchmarking the PC step's effect; see CLAUDE.md.

"""
    EFBFP(; vartheta_0, vartheta_1, tau_0,
            delta_rule, sigma_rule, delta_exp, sigma_exp, sigma_scale)
    EFBFP(preset::Symbol; kwargs...)

Extrapolated forward–backward–forward method (manuscript Algorithm 2) = EPCM
without the projection–contraction step. Parameters: `0 < vartheta_1 <
vartheta_0`, `tau_0 > 0`, and the σ_k / δ_k power-law sequences shared with EPCM
(`sigma_exp ∈ (0,1]`, `delta_exp > 1`). No γ, no ζ. Validated at `solve` entry.
"""
struct EFBFP <: AbstractAlgorithm
    vartheta_0::Float64
    vartheta_1::Float64
    tau_0::Float64
    delta_rule::Symbol
    sigma_rule::Symbol
    delta_exp::Float64
    sigma_exp::Float64
    sigma_scale::Float64

    function EFBFP(; vartheta_0::Float64, vartheta_1::Float64, tau_0::Float64,
                   delta_rule::Symbol, sigma_rule::Symbol,
                   delta_exp::Float64, sigma_exp::Float64, sigma_scale::Float64)
        return new(vartheta_0, vartheta_1, tau_0,
                   delta_rule, sigma_rule, delta_exp, sigma_exp, sigma_scale)
    end
end

"""
EFBFP presets keyed by `Symbol` (`:P1`–`:P5`) — per-problem manuscript defaults
/ s20 LHS search CENTRE (per-problem `tau_0` mirrors `EPCM_PRESETS`; ϑ_0 = 0.2,
ϑ_1 = 0.1). NOTE: EFBFP has no proven upper bound on ϑ_0 (no convergence theorem
yet), so the defaults stay modest and s20 searches a heuristic envelope. Tuned
winners are written by s20 to the autogenerated presets file (consumed by s30).
"""
const EFBFP_PRESETS = Dict{Symbol,NamedTuple}(
    :P1 => (vartheta_0=0.2, vartheta_1=0.1, tau_0=1.0,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P2 => (vartheta_0=0.2, vartheta_1=0.1, tau_0=1.0e-4,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P3 => (vartheta_0=0.2, vartheta_1=0.1, tau_0=0.1,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P4 => (vartheta_0=0.2, vartheta_1=0.1, tau_0=0.5,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P5 => (vartheta_0=0.2, vartheta_1=0.1, tau_0=1.0,
            delta_rule=:power, sigma_rule=:power,
            delta_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
)

function EFBFP(preset::Symbol; kwargs...)
    haskey(EFBFP_PRESETS, preset) ||
        throw(ArgumentError("Unknown EFBFP preset :$preset. Known: $(join(sort(collect(keys(EFBFP_PRESETS))), ", "))"))
    return EFBFP(; merge(EFBFP_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{EFBFP})    = "EFBFP"
version(::Type{EFBFP}) = v"1.1.0"   # 1.0.0→1.1.0: stepsize threshold corrected ϑ₀·τ_k→ϑ₀/τ_k (matches paper/proof) + half-split admissibility ϑ₀<1/√6 (Theorem thm:efbfp). config_hash changes ⟹ fresh results.

# ============================================================================
# AEFBFP — Adaptive Extrapolated Forward–Backward–Forward (manuscript Alg 3)
# ============================================================================
#
# AEFBFP = EFBFP with the min-rule self-adaptive stepsize (Malitsky–Tam / IFRAB
# form) replacing the ϑ-conditional rule:
#   τ_{k+1} = min{ μ‖z_k−z_{k-1}‖ / ‖B(z_k)−B(z_{k-1})‖, τ_k + ξ_k }  (B differs)
#         or  τ_k + ξ_k                                               (otherwise)
# with μ ∈ (0,1) and Σξ_k < ∞ (ξ_k = 1/(k+1)^xi_exp, xi_exp > 1). No theorem yet.

"""
    AEFBFP(; mu, tau_0, xi_rule, sigma_rule, xi_exp, sigma_exp, sigma_scale)
    AEFBFP(preset::Symbol; kwargs...)

Adaptive extrapolated forward–backward–forward method (manuscript Algorithm 3) =
EFBFP with the min-rule self-adaptive stepsize. Parameters: `mu ∈ (0,1)`,
`tau_0 > 0`, the summable additive sequence ξ_k = 1/(k+1)^`xi_exp` (`xi_exp > 1`),
and the σ_k power-law sequence shared with EPCM. Validated at `solve` entry.
"""
struct AEFBFP <: AbstractAlgorithm
    mu::Float64
    tau_0::Float64
    xi_rule::Symbol
    sigma_rule::Symbol
    xi_exp::Float64
    sigma_exp::Float64
    sigma_scale::Float64

    function AEFBFP(; mu::Float64, tau_0::Float64,
                    xi_rule::Symbol, sigma_rule::Symbol,
                    xi_exp::Float64, sigma_exp::Float64, sigma_scale::Float64)
        return new(mu, tau_0, xi_rule, sigma_rule, xi_exp, sigma_exp, sigma_scale)
    end
end

"""
AEFBFP presets keyed by `Symbol` (`:P1`–`:P5`) — s20 search CENTRE: μ = 0.5,
per-problem `tau_0` (mirrors `EPCM_PRESETS`), ξ_k = 1/(k+1)² (xi_exp = 2),
σ_k = 1/(k+2). Tuned winners written by s20 to the autogenerated presets file.
"""
const AEFBFP_PRESETS = Dict{Symbol,NamedTuple}(
    :P1 => (mu=0.35, tau_0=1.0,
            xi_rule=:power, sigma_rule=:power,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P2 => (mu=0.35, tau_0=1.0e-4,
            xi_rule=:power, sigma_rule=:power,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P3 => (mu=0.35, tau_0=0.1,
            xi_rule=:power, sigma_rule=:power,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P4 => (mu=0.35, tau_0=0.5,
            xi_rule=:power, sigma_rule=:power,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P5 => (mu=0.35, tau_0=1.0,
            xi_rule=:power, sigma_rule=:power,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
)

function AEFBFP(preset::Symbol; kwargs...)
    haskey(AEFBFP_PRESETS, preset) ||
        throw(ArgumentError("Unknown AEFBFP preset :$preset. Known: $(join(sort(collect(keys(AEFBFP_PRESETS))), ", "))"))
    return AEFBFP(; merge(AEFBFP_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{AEFBFP})    = "AEFBFP"
version(::Type{AEFBFP}) = v"1.1.0"   # 1.0.0→1.1.0: solver UNCHANGED, but admissibility tightened to μ<1/√6 (Theorem thm:aefbfp). Bump is mandatory so s20 promotion (version-keyed) does NOT rank the old out-of-theory μ≈0.64 s20 rows (still in DB under 1.0.0) against the new μ≤0.40 winners.

# ============================================================================
# MAEFBFP — Modified Adaptive Extrapolated Forward–Backward–Forward
# ============================================================================
#
# MAEFBFP = AEFBFP with the min-rule factor μ replaced by
#   α_n + β_n μ,
# where α_n ≥ 0, β_n ≥ 1, α_n → 0, and β_n → 1. This repo encodes the
# sequences as
#   α_n = alpha_scale / (n+1)^alpha_exp,     alpha_scale ≥ 0, alpha_exp > 0
#   β_n = 1 + beta_scale / (n+1)^beta_exp,   beta_scale ≥ 0, beta_exp > 0
# so the original AEFBFP is recovered at alpha_scale = beta_scale = 0.
#
# This is a repo-side modified variant, not a source-paper algorithm. To stay
# inside the AEFBFP admissibility envelope at every iteration, `solve` enforces
# the sufficient uniform bound
#   α_0 + β_0 μ = alpha_scale + (1 + beta_scale) μ < 1/√6.

"""
    MAEFBFP(; mu, tau_0, xi_rule, sigma_rule,
              alpha_scale, alpha_exp, beta_scale, beta_exp,
              xi_exp, sigma_exp, sigma_scale)
    MAEFBFP(preset::Symbol; kwargs...)

Modified adaptive extrapolated forward–backward–forward method = AEFBFP with
the min-rule factor `mu` replaced by the iteration-dependent coefficient
`alpha_n + beta_n * mu`, where

  - `alpha_n = alpha_scale / (n+1)^alpha_exp`, with `alpha_scale ≥ 0`,
    `alpha_exp > 0`, so `alpha_n → 0`;
  - `beta_n = 1 + beta_scale / (n+1)^beta_exp`, with `beta_scale ≥ 0`,
    `beta_exp > 0`, so `beta_n ≥ 1` and `beta_n → 1`.

The summable additive sequence `ξ_k = 1/(k+1)^xi_exp` (`xi_exp > 1`) and the
Halpern weights `σ_k` are inherited from AEFBFP/EPCM. Validated at `solve`
entry, including the sufficient uniform bound
`alpha_scale + (1 + beta_scale) * mu < 1/sqrt(6)`.
"""
struct MAEFBFP <: AbstractAlgorithm
    mu::Float64
    tau_0::Float64
    xi_rule::Symbol
    sigma_rule::Symbol
    alpha_scale::Float64
    alpha_exp::Float64
    beta_scale::Float64
    beta_exp::Float64
    xi_exp::Float64
    sigma_exp::Float64
    sigma_scale::Float64

    function MAEFBFP(; mu::Float64, tau_0::Float64,
                     xi_rule::Symbol, sigma_rule::Symbol,
                     alpha_scale::Float64, alpha_exp::Float64,
                     beta_scale::Float64, beta_exp::Float64,
                     xi_exp::Float64, sigma_exp::Float64, sigma_scale::Float64)
        return new(mu, tau_0, xi_rule, sigma_rule,
                   alpha_scale, alpha_exp, beta_scale, beta_exp,
                   xi_exp, sigma_exp, sigma_scale)
    end
end

"""
MAEFBFP presets keyed by `Symbol` (`:P1`–`:P5`) — seeded from AEFBFP's centre,
with mild nontrivial sequence modifiers:
  α_n = 0.02/(n+1)^2,  β_n = 1 + 0.05/(n+1)^2.
These are bootstrap defaults only; s20 should be rerun before using MAEFBFP in
comparative reporting.
"""
const MAEFBFP_PRESETS = Dict{Symbol,NamedTuple}(
    :P1 => (mu=0.30, tau_0=1.0,
            xi_rule=:power, sigma_rule=:power,
            alpha_scale=0.02, alpha_exp=2.0,
            beta_scale=0.05, beta_exp=2.0,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P2 => (mu=0.30, tau_0=1.0e-4,
            xi_rule=:power, sigma_rule=:power,
            alpha_scale=0.02, alpha_exp=2.0,
            beta_scale=0.05, beta_exp=2.0,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P3 => (mu=0.30, tau_0=0.1,
            xi_rule=:power, sigma_rule=:power,
            alpha_scale=0.02, alpha_exp=2.0,
            beta_scale=0.05, beta_exp=2.0,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P4 => (mu=0.30, tau_0=0.5,
            xi_rule=:power, sigma_rule=:power,
            alpha_scale=0.02, alpha_exp=2.0,
            beta_scale=0.05, beta_exp=2.0,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
    :P5 => (mu=0.30, tau_0=1.0,
            xi_rule=:power, sigma_rule=:power,
            alpha_scale=0.02, alpha_exp=2.0,
            beta_scale=0.05, beta_exp=2.0,
            xi_exp=2.0, sigma_exp=1.0, sigma_scale=1.0),
)

function MAEFBFP(preset::Symbol; kwargs...)
    haskey(MAEFBFP_PRESETS, preset) ||
        throw(ArgumentError("Unknown MAEFBFP preset :$preset. Known: $(join(sort(collect(keys(MAEFBFP_PRESETS))), ", "))"))
    return MAEFBFP(; merge(MAEFBFP_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{MAEFBFP})    = "MAEFBFP"
version(::Type{MAEFBFP}) = v"1.0.0"

# ============================================================================
# VAFBS — Viscosity-Approximation Forward–Backward Splitting (Thong2019 Alg 3.1)
# ============================================================================
#
# Source: Duong Viet Thong and Prasit Cholamjiak, "Strong convergence of a
# forward-backward splitting method with a new step size for solving monotone
# inclusions," Computational and Applied Mathematics 38, Article 94 (2019).
# https://doi.org/10.1007/s40314-019-0855-z. Algorithm 3.1.
#
# Paper notation: solve 0 ∈ A(x) + B(x) with A single-valued monotone Lipschitz
# and B maximal monotone. In this repo's convention, that maps directly to
# `prob.B` (paper A) and `prob.resolvent_A` (paper B).
#
# Iteration:
#   y_n = J^B_{λ_n}(x_n - λ_n A x_n), with λ_n chosen by backtracking over
#         {δ, δℓ, δℓ², ...} until
#           λ_n⟨A x_n - A y_n, x_n - y_n⟩ ≤ μ‖x_n - y_n‖²
#   d_n = x_n - y_n - λ_n(A x_n - A y_n)
#   η_n = (1-μ)‖x_n-y_n‖² / ‖d_n‖²
#   z_n = x_n - γ η_n d_n
#   x_{n+1} = α_n f(x_n) + (1-α_n) z_n
#
# The paper assumes `f` is a contraction. For this repo, we encode the chosen
# contraction `f(x) = c x` via the scalar field `f_scale = c`, keeping the
# algorithm hashable and reproducible (no Function-valued fields). The default
# chosen with the user is `f_scale = 0.9`.

"""
    VAFBS(; delta, ell, mu, gamma, alpha_rule, alpha_scale, f_scale)
    VAFBS(preset::Symbol; kwargs...)

Viscosity-approximation forward-backward splitting method
(Thong–Cholamjiak 2019, Algorithm 3.1).

Fields:
  - `delta > 0` : top line-search step (`δ` in the paper)
  - `ell ∈ (0,1)` : geometric shrink factor (`ℓ` in the paper)
  - `mu ∈ (0,1)` : Armijo-like acceptance parameter (`μ`)
  - `gamma ∈ (0,2)` : correction factor (`γ`)
  - `alpha_rule = :c_over_n` : `α_n = alpha_scale / n`
  - `alpha_scale ∈ (0,1)` : coefficient in `α_n`
  - `f_scale ∈ [0,1)` : contraction `f(x) = f_scale * x`
"""
struct VAFBS <: AbstractAlgorithm
    delta::Float64
    ell::Float64
    mu::Float64
    gamma::Float64
    alpha_rule::Symbol
    alpha_scale::Float64
    f_scale::Float64

    function VAFBS(; delta::Float64, ell::Float64, mu::Float64, gamma::Float64,
                   alpha_rule::Symbol, alpha_scale::Float64, f_scale::Float64)
        return new(delta, ell, mu, gamma, alpha_rule, alpha_scale, f_scale)
    end
end

# VAFBS_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
# (loaded via includes.jl); the T(:preset) constructor below resolves it at call time.

function VAFBS(preset::Symbol; kwargs...)
    haskey(VAFBS_PRESETS, preset) ||
        throw(ArgumentError("Unknown VAFBS preset :$preset. Known: $(join(sort(collect(keys(VAFBS_PRESETS))), ", "))"))
    return VAFBS(; merge(VAFBS_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{VAFBS})    = "VAFBS"
version(::Type{VAFBS}) = v"1.0.0"

# ============================================================================
# MDITSM — Modified Tseng Splitting Method with Double Inertial Steps
#           (Wang2023 Alg 3.1)
# ============================================================================
#
# Source: Wang et al. 2023, Algorithm 3.1.
#
# Paper notation: solve 0 ∈ A(x) + B(x) with A single-valued monotone Lipschitz
# and B maximal monotone. In this repo's convention, that maps to:
#   paper A ↔ prob.B
#   paper B ↔ prob.resolvent_A
#
# Iteration:
#   w_n = x_n + α_n (x_n - x_{n-1})
#   z_n = x_n + β_n (x_n - x_{n-1})
#   y_n = J^B_{λ_n}(w_n - λ_n A w_n)
#   λ_{n+1} = min{ (μ_n+μ)||w_n-y_n|| / ||A w_n-A y_n||, λ_n + p_n }
#             if A w_n ≠ A y_n, else λ_n + p_n
#   x_{n+1} = (1-θ_n) z_n + θ_n (y_n - λ_n (A y_n - A w_n))
#
# The source paper reports several experiment-specific parameter choices. For
# this repo, `:paper` uses the main Example 5.1 compressed-sensing / LASSO
# comparison setting, and `:P1`–`:P5` are initially seeded to that same source
# configuration until s20 tuning is run.

"""
    MDITSM(; mu, lambda_1,
             alpha_rule, alpha_scale, alpha_base,
             beta_rule, beta_cap, beta_shift,
             theta_rule, theta_cap, theta_shift,
             mu_rule, mu_scale, mu_exp,
             p_rule, p_scale, p_exp)
    MDITSM(preset::Symbol; kwargs...)

Modified Tseng splitting method with double inertial steps
(Wang et al. 2023, Algorithm 3.1).

Fields:
  - `mu ∈ (0,1)` : Wang's adaptive-step parameter `μ`
  - `lambda_1 > 0` : initial stepsize `λ₁`
  - `alpha_rule = :one_minus_scale_over_base_pow_n` :
    `α_n = 1 - alpha_scale / alpha_base^n`
  - `beta_rule = :cap_minus_inv_n_plus_shift` :
    `β_n = beta_cap - 1/(beta_shift + n)`
  - `theta_rule = :cap_minus_inv_n_plus_shift` :
    `θ_n = theta_cap - 1/(theta_shift + n)`
  - `mu_rule = :scale_over_n_pow` or `:zero` :
    `μ_n = mu_scale / n^mu_exp` or `0`
  - `p_rule = :scale_over_n_pow` or `:zero` :
    `p_n = p_scale / n^p_exp` or `0`
"""
struct MDITSM <: AbstractAlgorithm
    mu::Float64
    lambda_1::Float64
    alpha_rule::Symbol
    alpha_scale::Float64
    alpha_base::Float64
    beta_rule::Symbol
    beta_cap::Float64
    beta_shift::Float64
    theta_rule::Symbol
    theta_cap::Float64
    theta_shift::Float64
    mu_rule::Symbol
    mu_scale::Float64
    mu_exp::Float64
    p_rule::Symbol
    p_scale::Float64
    p_exp::Float64

    function MDITSM(; mu::Float64, lambda_1::Float64,
                    alpha_rule::Symbol, alpha_scale::Float64, alpha_base::Float64,
                    beta_rule::Symbol, beta_cap::Float64, beta_shift::Float64,
                    theta_rule::Symbol, theta_cap::Float64, theta_shift::Float64,
                    mu_rule::Symbol, mu_scale::Float64, mu_exp::Float64,
                    p_rule::Symbol, p_scale::Float64, p_exp::Float64)
        return new(mu, lambda_1,
                   alpha_rule, alpha_scale, alpha_base,
                   beta_rule, beta_cap, beta_shift,
                   theta_rule, theta_cap, theta_shift,
                   mu_rule, mu_scale, mu_exp,
                   p_rule, p_scale, p_exp)
    end
end

# MDITSM_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
# (loaded via includes.jl); the T(:preset) constructor below resolves it at call time.

function MDITSM(preset::Symbol; kwargs...)
    haskey(MDITSM_PRESETS, preset) ||
        throw(ArgumentError("Unknown MDITSM preset :$preset. Known: $(join(sort(collect(keys(MDITSM_PRESETS))), ", "))"))
    return MDITSM(; merge(MDITSM_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{MDITSM})    = "MDITSM"
version(::Type{MDITSM}) = v"1.0.0"

# ============================================================================
# MFRBSM — Modified Forward–Backward Splitting Method
#          (Hieu–Anh–Muu 2021 Algorithm 3.1)
# ============================================================================
#
# Source: Dang Van Hieu, Pham Ky Anh, and Le Dung Muu,
# "Modified forward–backward splitting method for variational inclusions,"
# 4OR 19, 127–160 (2021). https://doi.org/10.1007/s10288-020-00440-3.
#
# Paper iteration:
#   x_{n+1} = J^A_{λ_n}(x_n - λ_n B x_n - λ_{n-1}(B x_n - B x_{n-1}))
#   λ_{n+1} = min{ λ_n, μ ||x_{n+1}-x_n|| / ||B x_{n+1} - B x_n|| }.
#
# For this repo, `:paper` uses the numerical-section setting
# λ_{-1} = λ_0 = 0.1 and μ = 0.49.

"""
    MFRBSM(; lambda_minus1, lambda_0, mu)
    MFRBSM(preset::Symbol; kwargs...)

Modified forward-backward splitting method with the source paper's adaptive
nonincreasing stepsize rule (Hieu et al. 2021, Algorithm 3.1).
"""
struct MFRBSM <: AbstractAlgorithm
    lambda_minus1::Float64
    lambda_0::Float64
    mu::Float64

    function MFRBSM(; lambda_minus1::Float64, lambda_0::Float64, mu::Float64)
        return new(lambda_minus1, lambda_0, mu)
    end
end

# MFRBSM_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
function MFRBSM(preset::Symbol; kwargs...)
    haskey(MFRBSM_PRESETS, preset) ||
        throw(ArgumentError("Unknown MFRBSM preset :$preset. Known: $(join(sort(collect(keys(MFRBSM_PRESETS))), ", "))"))
    return MFRBSM(; merge(MFRBSM_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{MFRBSM})    = "MFRBSM"
version(::Type{MFRBSM}) = v"1.0.0"

# ============================================================================
# RFBSM — Relaxed Forward–Backward Splitting Method
#         (Cholamjiak2021 Algorithm 1)
# ============================================================================
#
# Source: Prasit Cholamjiak, Dang Van Hieu, and Yeol Je Cho,
# "Relaxed forward–backward splitting methods for solving variational
# inclusions and applications,"
# Journal of Scientific Computing 88, Article 85 (2021).
# https://doi.org/10.1007/s10915-021-01608-7.
#
# Paper notation matches the repo convention directly: A is set-valued and B is
# single-valued. Iteration:
#   y_n = J^A_{λ_n}(x_n - λ_n B x_n)
#   x_{n+1} = (1-θ)x_n + θ y_n + θ λ_n (B x_n - B y_n)
#   λ_{n+1} = min{ λ_n, μ ||x_n-y_n|| / ||B x_n - B y_n|| }
#
# For this repo, `:paper` uses the signal-recovery setting reported in Section 5:
# λ_0 = 1, θ = 1, μ = 0.9.

"""
    RFBSM(; lambda_0, theta, mu)
    RFBSM(preset::Symbol; kwargs...)

Relaxed forward-backward splitting method with the paper's new stepsizes
(Cholamjiak et al. 2021, Algorithm 1).
"""
struct RFBSM <: AbstractAlgorithm
    lambda_0::Float64
    theta::Float64
    mu::Float64

    function RFBSM(; lambda_0::Float64, theta::Float64, mu::Float64)
        return new(lambda_0, theta, mu)
    end
end

# RFBSM_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
function RFBSM(preset::Symbol; kwargs...)
    haskey(RFBSM_PRESETS, preset) ||
        throw(ArgumentError("Unknown RFBSM preset :$preset. Known: $(join(sort(collect(keys(RFBSM_PRESETS))), ", "))"))
    return RFBSM(; merge(RFBSM_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{RFBSM})    = "RFBSM"
version(::Type{RFBSM}) = v"1.0.0"

# ============================================================================
# IRFBSM — Inertial Relaxed Forward–Backward Splitting Method
#          (Cholamjiak2021 Algorithm 2)
# ============================================================================
#
# 
# Source: Prasit Cholamjiak, Dang Van Hieu, and Yeol Je Cho,
# "Relaxed forward–backward splitting methods for solving variational
# inclusions and applications,"
# Journal of Scientific Computing 88, Article 85 (2021).
# https://doi.org/10.1007/s10915-021-01608-7.
#
# Paper notation matches the repo convention directly. Iteration:
#   w_n = x_n + α(x_n - x_{n-1})
#   y_n = J^A_{λ_n}(w_n - λ_n B w_n)
#   x_{n+1} = (1-θ)w_n + θ y_n + θ λ_n (B w_n - B y_n)
#   λ_{n+1} = min{ λ_n, μ ||w_n-y_n|| / ||B w_n - B y_n|| }
#
# For this repo, `:paper` uses the signal-recovery setting reported in Section 5:
# λ_0 = 1, θ = 1, μ = 0.9, α = 0.1.

"""
    IRFBSM(; lambda_0, theta, mu, alpha)
    IRFBSM(preset::Symbol; kwargs...)

Inertial relaxed forward-backward splitting method with the paper's new
stepsizes (Cholamjiak et al. 2021, Algorithm 2).
"""
struct IRFBSM <: AbstractAlgorithm
    lambda_0::Float64
    theta::Float64
    mu::Float64
    alpha::Float64

    function IRFBSM(; lambda_0::Float64, theta::Float64, mu::Float64, alpha::Float64)
        return new(lambda_0, theta, mu, alpha)
    end
end

# IRFBSM_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
function IRFBSM(preset::Symbol; kwargs...)
    haskey(IRFBSM_PRESETS, preset) ||
        throw(ArgumentError("Unknown IRFBSM preset :$preset. Known: $(join(sort(collect(keys(IRFBSM_PRESETS))), ", "))"))
    return IRFBSM(; merge(IRFBSM_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{IRFBSM})    = "IRFBSM"
version(::Type{IRFBSM}) = v"1.0.0"

# ============================================================================
# MTTM — Mann Tseng-Type Method (Gibali2018 Alg 1)
# ============================================================================
#
# Source: Aviv Gibali and Duong Viet Thong, "Tseng type methods for solving
# inclusion problems and its applications," Calcolo 55, Article 49 (2018).
# https://doi.org/10.1007/s10092-018-0292-1. Algorithm 1. Manuscript line 1607
# (first sentence):
#   λ_0 = 7.55, μ = 0.85, α_n = 1/n, β_n = (n-1)/(2n)
# Source examples are SCFP (Ex 3) and sparse signal recovery (Ex 4), neither
# of which is in our problem set — so :paper = :P1 = :P2 = :P3 initially.

"""
    MTTM(; lambda_0, mu, alpha_rule, beta_rule)
    MTTM(preset::Symbol; kwargs...)

Mann Tseng-type method (Gibali2018 Algorithm 1). Manuscript §Parameter choices
line 1607.

`alpha_rule = :inv_n` ↦ α_n = 1/n.
`beta_rule = :n_minus_1_over_2n` ↦ β_n = (n-1)/(2n).
"""
struct MTTM <: AbstractAlgorithm
    lambda_0::Float64
    mu::Float64
    alpha_rule::Symbol
    beta_rule::Symbol

    function MTTM(; lambda_0::Float64, mu::Float64,
                  alpha_rule::Symbol, beta_rule::Symbol)
        return new(lambda_0, mu, alpha_rule, beta_rule)
    end
end

# MTTM_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
# (loaded via includes.jl); the T(:preset) constructor below resolves it at call time.

function MTTM(preset::Symbol; kwargs...)
    haskey(MTTM_PRESETS, preset) ||
        throw(ArgumentError("Unknown MTTM preset :$preset. Known: $(join(sort(collect(keys(MTTM_PRESETS))), ", "))"))
    return MTTM(; merge(MTTM_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{MTTM})    = "MTTM"
version(::Type{MTTM}) = v"1.0.0"

# ============================================================================
# IMTTM — Inertial Mann Tseng-Type Method (Tan2022a Alg 3.3)
# ============================================================================
#
# Source: Bing Tan and Sun Young Cho, "Strong convergence of inertial
# forward-backward methods for solving monotone inclusions," Applicable
# Analysis 101(15), 5386-5414 (2022).
# https://doi.org/10.1080/00036811.2021.1892080. Algorithm 3.3. Manuscript line
# 1607 (later sentences):
#   μ=0.5, α_n=1/(n+1), β_n=0.5(1−α_n), ε_n=100/(n+1)², θ=0.5.
#   λ_0=1 (default); λ_0=0.01 for P1 (Tan's Ex 5.1 adjustment, manuscript-cited).

"""
    IMTTM(; lambda_0, mu, theta, alpha_rule, beta_rule, epsilon_rule)
    IMTTM(preset::Symbol; kwargs...)

Inertial Mann Tseng-type method (Tan2022a Algorithm 3.3).

`alpha_rule = :inv_n_plus_1`    ↦ α_n = 1/(n+1).
`beta_rule = :tan`              ↦ β_n = 0.5·(1 − α_n).
`epsilon_rule = :hundred_inv_sq`↦ ε_n = 100/(n+1)².
"""
struct IMTTM <: AbstractAlgorithm
    lambda_0::Float64
    mu::Float64
    theta::Float64
    alpha_rule::Symbol
    beta_rule::Symbol
    epsilon_rule::Symbol

    function IMTTM(; lambda_0::Float64, mu::Float64, theta::Float64,
                   alpha_rule::Symbol, beta_rule::Symbol, epsilon_rule::Symbol)
        return new(lambda_0, mu, theta, alpha_rule, beta_rule, epsilon_rule)
    end
end

# IMTTM_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
# (loaded via includes.jl); the T(:preset) constructor below resolves it at call time.

function IMTTM(preset::Symbol; kwargs...)
    haskey(IMTTM_PRESETS, preset) ||
        throw(ArgumentError("Unknown IMTTM preset :$preset. Known: $(join(sort(collect(keys(IMTTM_PRESETS))), ", "))"))
    return IMTTM(; merge(IMTTM_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{IMTTM})    = "IMTTM"
version(::Type{IMTTM}) = v"1.0.0"

# ============================================================================
# IFRAB — Variable-Inertial Forward-Reflected-Anchored-Backward (Izuchukwu2023 Alg 4.5)
# ============================================================================
#
# Source: Chinedu Izuchukwu, Simeon Reich, Yekini Shehu, and Adeolu Taiwo,
# "Strong Convergence of Forward-Reflected-Backward Splitting Methods for
# Solving Monotone Inclusions with Applications to Image Restoration and
# Optimal Control," Journal of Scientific Computing 94(3), Article 73 (2023).
# https://doi.org/10.1007/s10915-023-02132-6. Algorithm 4.5 + stepsize eq 3.2.
# Manuscript lines 1609-1622: δ_0=0.1, δ_1=0.3, r̄=0.3, σ_n=0.005/(3n+25000),
# c_n=1/(n²+1), and ϑ_n = ϑ̄·n/(n+1) with ϑ̄=0.04 (per B2 post-review).

"""
    IFRAB(; delta_0, delta_1, rbar, vartheta_bar, sigma_rule, c_rule, vartheta_rule)
    IFRAB(preset::Symbol; kwargs...)

Variable-inertial forward-reflected-anchored-backward method (Izuchukwu2023
Algorithm 4.5).

`sigma_rule = :izuchukwu_sigma`  ↦ σ_n = 0.005/(3n + 25000).
`c_rule = :inv_n_sq_plus_1`      ↦ c_n = 1/(n² + 1).
`vartheta_rule = :n_over_n_plus_1` ↦ ϑ_n = ϑ̄ · n/(n+1).
"""
struct IFRAB <: AbstractAlgorithm
    delta_0::Float64
    delta_1::Float64
    rbar::Float64
    vartheta_bar::Float64
    sigma_rule::Symbol
    c_rule::Symbol
    vartheta_rule::Symbol

    function IFRAB(; delta_0::Float64, delta_1::Float64, rbar::Float64,
                   vartheta_bar::Float64, sigma_rule::Symbol, c_rule::Symbol,
                   vartheta_rule::Symbol)
        return new(delta_0, delta_1, rbar, vartheta_bar,
                   sigma_rule, c_rule, vartheta_rule)
    end
end

# IFRAB_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
# (loaded via includes.jl); the T(:preset) constructor below resolves it at call time.

function IFRAB(preset::Symbol; kwargs...)
    haskey(IFRAB_PRESETS, preset) ||
        throw(ArgumentError("Unknown IFRAB preset :$preset. Known: $(join(sort(collect(keys(IFRAB_PRESETS))), ", "))"))
    return IFRAB(; merge(IFRAB_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{IFRAB})    = "IFRAB"
version(::Type{IFRAB}) = v"1.0.0"

# ============================================================================
# SFRBM — Strongly-Convergent Forward-Reflected-Backward with Momentum (Yao2024 Alg 2)
# ============================================================================
#
# Source: Yonghong Yao, Abubakar Adamu, and Yekini Shehu,
# "Forward-Reflected-Backward Splitting Algorithms with Momentum: Weak, Linear
# and Strong Convergence Results," Journal of Optimization Theory and
# Applications 201(3), 1364-1397 (2024).
# https://doi.org/10.1007/s10957-024-02410-9. Algorithm 2. Manuscript lines
# 1623-1627: λ_{-1} = λ_0 = μ = 1e-4, θ = 10, β_k = 1/(5000(k+1)).

"""
    SFRBM(; lambda_minus1, lambda_0, mu, theta, beta_rule)
    SFRBM(preset::Symbol; kwargs...)

Strongly-convergent forward-reflected-backward with momentum (Yao2024
Algorithm 2).

`beta_rule = :yao` ↦ β_k = 1/(5000(k+1)).
"""
struct SFRBM <: AbstractAlgorithm
    lambda_minus1::Float64
    lambda_0::Float64
    mu::Float64
    theta::Float64
    beta_rule::Symbol

    function SFRBM(; lambda_minus1::Float64, lambda_0::Float64,
                   mu::Float64, theta::Float64, beta_rule::Symbol)
        return new(lambda_minus1, lambda_0, mu, theta, beta_rule)
    end
end

# SFRBM_PRESETS moved to jcode/configs/competitors_original_parameters_presets.jl
# (loaded via includes.jl); the T(:preset) constructor below resolves it at call time.

function SFRBM(preset::Symbol; kwargs...)
    haskey(SFRBM_PRESETS, preset) ||
        throw(ArgumentError("Unknown SFRBM preset :$preset. Known: $(join(sort(collect(keys(SFRBM_PRESETS))), ", "))"))
    return SFRBM(; merge(SFRBM_PRESETS[preset], NamedTuple(kwargs))...)
end

name(::Type{SFRBM})    = "SFRBM"
version(::Type{SFRBM}) = v"1.0.0"
